# Generated by Django 5.0.6 on 2024-06-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Numbers',
            new_name='Number',
        ),
        migrations.RenameField(
            model_name='number',
            old_name='num',
            new_name='number',
        ),
    ]
