# Generated by Django 5.0.6 on 2024-06-27 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_pokemon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='image',
        ),
    ]
